{{- if .Values.knativeDeploy }}
{{- else }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: configservr
  name: configserver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: configserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: configserver
    spec:
      containers:
      - env:
        - name: SQL_URL
          value: sapo-mariadb-prod-rds.cp4o1dqqp6vg.ap-southeast-1.rds.amazonaws.com
        - name: SQL_USERNAME
          value: sapo_fnb
        - name: SQL_PASSWORD
          value: aA4G7xTBeVE8LUn
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: 10.86.1.79:9092,10.86.1.106:9092,10.86.1.216:9092
        - name: ZOOKEEPER_CONNECT
          value: 10.86.1.216,10.86.1.106,10.86.1.79
        image: hub.bizweb.vn/fnb-configserver:fa6d52a-master
        imagePullPolicy: IfNotPresent
        name: configserver
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-05-23T02:56:21Z"
    lastUpdateTime: "2019-05-29T08:00:46Z"
    message: ReplicaSet "configserver-7cfc56b756" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-05-30T09:45:46Z"
    lastUpdateTime: "2019-05-30T09:45:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1